### ISSUE TITLE
update copyright statement?

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#114]
@josegonzalez license says

> Copyright (C) 2014 Jeff Lindsay

which I guess was copied from dokku , but ansible-dokku actually started much later and, to my knowledge, Jeff Lindsay has not contributed code to it.

**Comment by josegonzalez** [comment]
I guess we can update that. I actually don't know what we should do, is setting it to me with whatever the starting date of the project was okay? /shrug

**Comment by ltalirz** [comment]
Keep, sounds good
