### ISSUE TITLE
Latest version not available on Ansible Galaxy

### ISSUE THREAD

**Issue by nerg4l** [dokku/ansible-dokku#123]
## Description of problem

As of now, the latest version on Ansible Galaxy is v2021.9.5. Since that there were two releases.

### How reproducible

Always.

### Steps to Reproduce

1. Try to install v2021.11.7 with the following command: `ansible-galaxy role install dokku_bot.ansible_dokku,v2021.11.7`

#### Actual Results

```
Starting galaxy role install process
- downloading role 'ansible_dokku', owned by dokku_bot
[WARNING]: - dokku_bot.ansible_dokku was NOT installed successfully: - the
specified version (v2021.11.7) of dokku_bot.ansible_dokku was not found in the
list of available versions [...]
```

#### Expected Results

```
Starting galaxy role install process
- downloading role 'ansible_dokku', owned by dokku_bot
- downloading role from https://github.com/dokku/ansible-dokku/archive/v2021.11.7.tar.gz
- extracting dokku_bot.ansible_dokku to /builds/shiroi-usagi/builder/.ansible/roles/dokku_bot.ansible_dokku
- dokku_bot.ansible_dokku (v2021.11.7) was installed successfully
[...]
```

### `dokku report APP_NAME` output

-

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Dokku was installed via this ansible role on a physical machine and two DigitalOcean droplet.

### Additional information

See available versions on https://galaxy.ansible.com/dokku_bot/ansible_dokku

**Comment by ltalirz** [comment]
thanks for the note @nerg4l 

indeed the "publish to galaxy" step is skipped since we have some failing checks
Iet me try to have a look

**Comment by ltalirz** [comment]
Will let you know when the next release is out; should be in a few h

**Comment by ltalirz** [comment]
done! https://galaxy.ansible.com/dokku_bot/ansible_dokku
