### ISSUE TITLE
Support for `git:from-image`?

### ISSUE THREAD

**Issue by fr3fou** [dokku/ansible-dokku#124]
The `git:from-image` plugin has not been implemented in the ansible library yet, it'd be of great use to deploy services like Meilisearch or others that don't have plugins implemented yet. Are there any plans on implmenting this in the future?

**Comment by ltalirz** [comment]
hey @fr3fou , I'm not going to work on it personally but you're most welcome to give it a try and I will be happy to review the PR.

the code to look at for inspiration would probably be https://github.com/dokku/ansible-dokku/blob/master/library/dokku_git_sync.py
