### ISSUE TITLE
dokku_builder: support changing the build directory

### ISSUE THREAD

**Issue by fr3fou** [dokku/ansible-dokku#128]
https://dokku.com/docs/deployment/builders/builder-management/#changing-the-build-directory

This functionality is really crucial to monorepo setups, so it'd be of great use to many users.

**Comment by ltalirz** [comment]
as always, PR welcome ;-)

**Comment by fr3fou** [comment]
I'd be glad to contribute, but I'm not sure how to implement this. Mind giving me some guidelines? Either here or over Slack is fine

**Comment by josegonzalez** [comment]
You probably actually want to create a `dokku_builder` module, not change the `dokku_clone` module. It would be similar to something like the `dokku_registry` module probably.
