### ISSUE TITLE
Support for running `detached` apps?

### ISSUE THREAD

**Issue by fr3fou** [dokku/ansible-dokku#131]
I'm trying to deploy cAdvisor on my server and noticed that If I try to use the `dokku_docker_options` library with the `--detach=true` option, I would get the following error:
![image](https://user-images.githubusercontent.com/1344906/142775285-67efd4b7-fd69-48ca-95d4-58f89459c102.png)
What would be a clean way to implement running apps in `detached` mode?

**Comment by ltalirz** [comment]
I don't know enough about what you're trying to accomplish here. Thoughts @josegonzalez ?

**Comment by josegonzalez** [comment]
All containers already run in detached mode, you don't need to add that flag.
