### ISSUE TITLE
How should I configure HTTP Basic Auth?

### ISSUE THREAD

**Issue by fr3fou** [dokku/ansible-dokku#133]
I have to protect some internal tools like `loki` and would like to use the https://github.com/dokku/dokku-http-auth plugin. 
I can easily install it via the `dokku_plugins` module / library, but how am I supposed to enable it per app using Ansible? Running the commands directly using the `command` module seems like a workaround and I'd like to know what's the recommended way to achieve this.

**Comment by ltalirz** [comment]
For any plugin, if there's no module, either one needs to use `command`/`shell` or someone needs to write one ;-) Always welcome, of course

**Comment by fr3fou** [comment]
If I were to write one, how should I ensure the plugin is installed?

**Comment by ltalirz** [comment]
For the tests you mean?

See the edits to `converge.yml` in this PR that adds modules for the `dokku-acl` plugin
