### ISSUE TITLE
dokku-daemon still needed?

### ISSUE THREAD

**Issue by robyurkowski** [dokku/ansible-dokku#167]
## Description of problem

I was looking through the role which I've used to set up and manage my Dokku for a while and attempting to comprehend the installation process and how it differs from the main Dokku bootstrap.sh script.

I noticed that this repository (which I understand is... maybe not out of date, but undergoing some transition issues, perhaps) is installing dokku-daemon [here](https://github.com/dokku/ansible-dokku/blob/master/tasks/dokku-daemon.yml), while the bootstrap script seems to omit it and I couldn't find reference to it in the Debian package's requirements either.

Indeed, I actually noticed that some of the main documentation seems to suggest that [Dokku doesn't run a daemon](https://github.com/dokku/dokku/blob/d301f68b906ceeae54c4b5da60f46d4da0370112/docs/getting-started/upgrading/index.md?plain=1#L7).

Is it still required? Regardless, I'm happy to contribute in either removing it or updating the documentation to reflect its use.

Thanks a bundle in advance!

**Comment by josegonzalez** [comment]
It can probably be removed, dokku doesn't use it by default and its unmaintained.

**Comment by robyurkowski** [comment]
Thanks! I'll try and get a PR in within the next week or two to yank it.
