### ISSUE TITLE
dokku_ports doesn't use the new 0.31+ ports commands, thus crashes

### ISSUE THREAD

**Issue by laurenskling** [dokku/ansible-dokku#168]
## Description of problem

```
fatal: [xxx.myserver.xxx]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "app": "myapp",
            "mappings": [
                "http:80:1337",
                "https:443:1337"
            ],
            "state": "present"
        }
    },
    "meta": {
        "error": "Command 'dokku --quiet proxy:ports-set myapp http:80:1337 https:443:1337' returned non-zero exit status 1.",
        "present": false
    },
    "msg": "Command 'dokku --quiet proxy:ports-set myapp http:80:1337 https:443:1337' returned non-zero exit status 1."
}
```
So manually on my server, I reproduce:
```
myuser@myserver:~# dokku proxy:ports-set myapp http:80:1337 https:443:1337
 !     Invalid plugin subcommand call: ports-set
```

this is because ports management changed in 0.31: https://dokku.com/docs/networking/port-management/

### How reproducible
use dokku 0.31+, use ansible dokku_ports 

## Environment Information

this command fails :/ sorry

### How (deb/make) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

I installed Dokku on a VPS and trying to get ansible to install my projects

**Comment by ltalirz** [comment]
https://github.com/dokku/ansible-dokku/issues/169

**Comment by marcoklein** [comment]
Also related to #159 if you installed via Ansible Galaxy. If I pull latest master and drop that in the `roles` folder the ports plugin works just fine.

**Comment by strugee** [comment]
I can confirm that upgrading from v2021.11.28 to v2024.3.13 fixes this issue for me. Thank you!

**Comment by ltalirz** [comment]
Great, I'll close this then. Should something still need to be fixed, feel free to reopen
