### ISSUE TITLE
How to install and use ansible-dokku?

### ISSUE THREAD

**Issue by alexislefebvre** [dokku/ansible-dokku#194]
## Description of problem

I'm relatively new to Ansible and never used Dokku before.

I'm trying to install Dokku through Ansible, but I don't know what I'm expected to do.

The README shows some YAML examples but the paths of the files are not explained.

What dependencies are required to be able to use `dokku_bot.ansible_dokku`? How do we install them?

### Steps to Reproduce

1. Try to install ansible-dokku
2. ?

#### Actual Results

Nothing.

## Environment Information

.

### `dokku report APP_NAME` output
.

### How (deb/make) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

.

### Additional information

```shell
$ ansible-playbook --version
ansible-playbook [core 2.17.1]
  config file = None
  configured module search path = ['/home/[…]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/[…]/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/[…]/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/[…]/.local/bin/ansible-playbook
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by alexislefebvre** [comment]
Update:

I found how to install the role:

```shell
ansible-galaxy role install dokku_bot.ansible_dokku
```

**Comment by ltalirz** [comment]
I once started writing a blog post on this but then there were change requests and I did not have time to complete it - would that have helped you? https://github.com/dokku/dokku.github.io/blob/a04bb52f846586fcf8c3f18db5d8f25643929157/_posts/2021-09-XX-ansible-dokku.md

I currently don't have time to continue working on it, perhaps someone else can pick it up

@josegonzalez

**Comment by alexislefebvre** [comment]
> I once started writing a blog post on this but then there were change requests and I did not have time to complete it - would that have helped you? https://github.com/dokku/dokku.github.io/blob/a04bb52f846586fcf8c3f18db5d8f25643929157/_posts/2021-09-XX-ansible-dokku.md
> 
> I currently don't have time to continue working on it, perhaps someone else can pick it up
> 
> @josegonzalez

Thanks for the answer!

I took your article, added `role: dokku_bot.ansible_dokku` since it was missing, and now it conflicts with the custom rules I added to install Docker, I took them from the Dokku documentation.

I guess I'll have to call dokku through CLI instead of using a plugin, so that I can learn the basics of dokku first. Then I may reconsider using `ansible-dokku` later.
