### ISSUE TITLE
TASK[ansible-dokku : nginx:repository] Failure

### ISSUE THREAD

**Issue by weirdaze** [dokku/ansible-dokku#21]
Hi, I am using the role in my playbook to provision dokku in a digitalocean droplet. 

Here is my install_dokku.yml playbook: 
`---
- hosts: dev
  roles:
          - ansible-dokku
  vars:
          dokku_plugins:
                  - name: lets encrypt
                    url: https://github.com/dokku/dokku-letsencrypt.git
          dokku_hostname: dev.mydomain.com
          ansible_user: my_sudo_user`

Here is the error I get when I run the playbook:

`ansible-playbook -u my_sudo_user install_dokku.yml
PLAY [dev] **********************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [dev]

TASK [ansible-dokku : nginx:repository] **********************************************************************************************
fatal: [dev]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 8B3981E7A6852F782CC4951600A6F0A3C300EE8C", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key\ngpg: key 00A6F0A3C300EE8C: public key \"Launchpad Stable\" imported\ngpg: Total number processed: 1\ngpg:               imported: 1\ngpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key\ngpg: no writable keyring found: Not found\ngpg: error reading '[stdin]': General error\ngpg: import from '[stdin]' failed: General error\ngpg: Total number processed: 0", "rc": 1, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key\ngpg: key 00A6F0A3C300EE8C: public key \"Launchpad Stable\" imported\ngpg: Total number processed: 1\ngpg:               imported: 1\ngpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key\ngpg: no writable keyring found: Not found\ngpg: error reading '[stdin]': General error\ngpg: import from '[stdin]' failed: General error\ngpg: Total number processed: 0\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key", "gpg: key 00A6F0A3C300EE8C: public key \"Launchpad Stable\" imported", "gpg: Total number processed: 1", "gpg:               imported: 1", "gpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key", "gpg: no writable keyring found: Not found", "gpg: error reading '[stdin]': General error", "gpg: import from '[stdin]' failed: General error", "gpg: Total number processed: 0"], "stdout": "Executing: /tmp/apt-key-gpghome.1MJP7WDJcA/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 8B3981E7A6852F782CC4951600A6F0A3C300EE8C\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.1MJP7WDJcA/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 8B3981E7A6852F782CC4951600A6F0A3C300EE8C"]}`

Am I missing something? Do I need to enter apt-keys? kinda new to this. thanks!

**Comment by josegonzalez** [comment]
What is the host OS you are running against?

**Comment by josegonzalez** [comment]
Closing this as we now use the nginxinc.nginx role for installing nginx as of https://github.com/dokku/ansible-dokku/commit/bca6626ae903c8700e7a98fbb56f3a9694661797#diff-9dc9fefada8e345e038604d48f03abdf.

**Comment by leandroembu** [comment]
The problem occurred again a few weeks ago because the nginxinc.nginx role had not been updated in Ansible Galaxy. Wouldn't it be better to use the nginx package from the distro where we are going to install Dokku instead of adding a third party repo?

**Comment by ltalirz** [comment]
Cheers, the idea was that nginxinc.nginx takes care of any changes in configuration / ... that occur over the years, but if they are not reliable, one could switch

You'll need to support these distros / versions:
https://github.com/dokku/ansible-dokku?tab=readme-ov-file#platform-requirements
