### ISSUE TITLE
Add Molecule based role testing?

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#26]
> https://molecule.readthedocs.io/en/stable/

Interested?

It would give more guarantees about correctness of this role.

Thanks for the good work!

**Comment by josegonzalez** [comment]
Pull requests welcome!

**Comment by decentral1se** [comment]
Sure thing. Do you have any preference on what "driver" is used? Molecule has a selection of them, the most convenient one being Docker except for systemd issues which can be worked around. Another thought, if you or anyone on the project has a deal with Digital Ocean, Molecule can provision fresh DO hosts to run commands on. That would probably be quite a realistic testing environment. Perhaps they are open to donate some credit per month for this effort.

**Comment by josegonzalez** [comment]
Docker is fine for now.
