### ISSUE TITLE
TASK [ansible-dokku : docker repo] - The repository '...' does not have a Release file

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#27]
>    TASK [ansible-dokku : docker repo] *********************************************
>     An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'http://ppa.launchpad.net/nginx/stable/ubuntu sid Release' does not have a Release file.
>     fatal: [dokku.ansible-dokku-ubuntu-bionic]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1572051198.9144094-279798295025760/AnsiballZ_apt_repository.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1572051198.9144094-279798295025760/AnsiballZ_apt_repository.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1572051198.9144094-279798295025760/AnsiballZ_apt_repository.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_apt_repository_payload_0IkOg_/__main__.py\", line 554, in <module>\n  File \"/tmp/ansible_apt_repository_payload_0IkOg_/__main__.py\", line 546, in main\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 559, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'http://ppa.launchpad.net/nginx/stable/ubuntu sid Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Running this on a Ubuntu:Bionic host. Strangely enough, when I run this task again, it passes. The error shows that it is selecting "sid" as the `ansible_lsb.codename` which is also strange.

**Comment by decentral1se** [comment]
Comment in https://github.com/dokku/ansible-dokku/issues/14 might be related.

**Comment by ltalirz** [comment]
Looks related to this https://github.com/ansible/ansible/issues/19874 , i.e. an (open) ansible issue

**Comment by ltalirz** [comment]
Since an incorrect `ansible_lsb.codename` is an ansible issue that we can't fix here, I'm closing this now.
Feel free to reopen in case there is something that should be done in this reop.
