### ISSUE TITLE
bootstrap scripts fail

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#37]
While I've successfully ran the ansible-dokku role on a clean Ubuntu 18.04 VM (even including the postgres plugin), I'm not able to deploy apps to it because deployments fail to install the necessary buildpacks.
I suspect it is some sort of permissions issue, so I'm reporting it here in the ansible role repo.

I've been following the instructions for the ruby-getting-started-example:

On host (all worked fine):
``` 
$ dokku apps:create ruby-getting-started
$ dokku postgres:create railsdatabase
$ dokku postgres:link railsdatabase ruby-getting-started
$ sudo dokku ssh-keys:add leopold.talirz /path/to/key/file   # added a user for the deployment
```

On client:
```
$ git remote add dokku dokku@xxx:ruby-getting-started
$ git push dokku master
Enumerating objects: 401, done.
Counting objects: 100% (401/401), done.
Delta compression using up to 8 threads
Compressing objects: 100% (222/222), done.
Writing objects: 100% (401/401), 82.00 KiB | 27.33 MiB/s, done.
Total 401 (delta 153), reused 401 (delta 153)
remote: Resolving deltas: 100% (153/153), done.
-----> Cleaning up...
-----> Building ruby-getting-started from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
       Failed to download a Ruby executable for bootstrapping!

       This is most likely a temporary internal error. If the problem
       persists, make sure that you are not running a custom or forked
       version of the Heroku Ruby buildpack which may need updating.
remote: /tmp/buildpacks/01_buildpack-ruby/bin/compile: line 11: /tmp/tmp.dnts3sk0AK/bin/ruby: No such file or directory
To 148.187.96.129:ruby-getting-started
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@148.187.96.129:ruby-getting-started'
```

It is not an issue of the buildpack - similar problems occur e.g. for node/python
```
$ git push dokku master
Enumerating objects: 38, done.
Counting objects: 100% (38/38), done.
Delta compression using up to 8 threads
Compressing objects: 100% (35/35), done.
Writing objects: 100% (38/38), 15.65 KiB | 2.61 MiB/s, done.
Total 38 (delta 11), reused 0 (delta 0)
-----> Cleaning up...
-----> Building ltal-py from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: nodejs python
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version 12.x...
```
(here the script hangs forever)

I'd be glad for any pointers

**Comment by josegonzalez** [comment]
This doesn't sound like a buildpack or ansible issue, but instead an outbound proxying issue. Buildpacks would either fail or hang if they can't fetch files from S3 or wherever the buildpack specifies them.

Can you replicate this on a server based in the US on either Digitalocean or AWS? 

Might be easier to tackle this problem on slack...

**Comment by ltalirz** [comment]
Thanks, I hadn't thought of that.

Indeed the command before the error message is the [download of the buildpack](https://gitlab.nosolosoftware.es/dokku/buildpack-ruby-sqlite3/commit/ab47ae5541262a80ce2cb3c004b9652086156c66#f95e3559539d9613ac9a4fdc64330f178fc8869a_15_37).

However, copy-pasting the urls & versions I see there, it seems to me that there are no connection issues on my VM:
```
$ curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.5.5.tgz -o file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      11 18.4M   11 2094k    0     0  1599k      0  0:00:11  0:00:01  0:00:10 1598 93 18.4M   93 17.2M    0     0  7720k      0  0:00:02  0:00:02 --:--:-- 7716100 18.4M  100 18.4M    0     0  7852k      0  0:00:02  0:00:02 --:--:-- 7852k
```
Perhaps it is related to permissions in the `$RUBY_BOOTSTRAP_DIR` after all?
A permissions error only kicks in after the download and perhaps the 
`curl_retry_on_18` retries a few times?
What's the easiest way for me to figure out this directory, are there more detailed logs?

Anyhow, I'm happy to continue this on slack if you prefer, just let me know which channel to post in.

**Comment by josegonzalez** [comment]
@ltalirz i would check that said curl request runs fine within a docker container. Just run a random container - it can be herokuish or ubuntu - with that command.

**Comment by ltalirz** [comment]
You're absolutely correct, thanks for the quick help!
I'll check whether I find something on the topic and otherwise ask in the slack channel.
