### ISSUE TITLE
fix travis build on Debian

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#38]
The Travis builds on Debian currently fail when trying to update the apt cache as part of adding the nginx repository through `apt_repository`.

ansible does generally seem to have issues around apt cache updates on debian https://github.com/ansible/ansible/issues/30754 although our issue seems to be slightly different - note e.g. that the pre-task works fine:
https://github.com/dokku/ansible-dokku/blob/f49797ada7833e5f7ea9a85980cc992333858251/molecule/default/playbook.yml#L7
https://travis-ci.org/dokku/ansible-dokku/jobs/632124266#L493

I've verified that one can work around this by adding `update_cache: false` here https://github.com/dokku/ansible-dokku/blob/f49797ada7833e5f7ea9a85980cc992333858251/tasks/nginx.yml#L5
but then one ends up in the next ansible bug a few lines further down
https://github.com/dokku/ansible-dokku/blob/f49797ada7833e5f7ea9a85980cc992333858251/tasks/install.yml#L46
It turns out that `{{ ansible_lsb }}` is empty on debian https://github.com/ansible/ansible/issues/19874
https://travis-ci.org/ltalirz/ansible-dokku/jobs/632294325#L532

I'm a bit unsure how to proceed here... should we butcher up the role to work around ansible's debian bugs or should we just wait until they are fixed?
Since I'm on Ubuntu, perhaps someone actually using debian could continue this work?

**Comment by ltalirz** [comment]
On the other hand, there seem to be ansible roles - using the same debian docker image - where it works fine:

Code: https://github.com/geerlingguy/ansible-role-docker/blob/736ad7f3518d5de2a91b851c2f7b781756a47f47/tasks/setup-Debian.yml#L36-L40
Travis: https://github.com/ansible/ansible/issues/19874

I must be missing something.

**Comment by ltalirz** [comment]
Since the geerlingguy.docker role seems to work and supports a wide range of operating systems, one could also consider to [depend on it for the docker part](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#galaxy-dependencies).

**Comment by josegonzalez** [comment]
That would be fine with me @ltalirz

**Comment by ltalirz** [comment]
I'm [almost there](https://travis-ci.org/ltalirz/ansible-dokku/builds/633196617?utm_medium=notification&utm_source=email) - but now I get an error when installing the dokku daemon:

https://travis-ci.org/ltalirz/ansible-dokku/builds/633196617?utm_medium=notification&utm_source=email
```
"sudo add-apt-repository universe", "Error: 'universe' invalid"
```
It seems  `universe` does not exist on debian - [only main, contrib and non-free](https://unix.stackexchange.com/a/113593/155909).

Looks to me like this would need to be fixed in the dokku-daemon makefile
https://github.com/dokku/dokku-daemon/blob/master/Makefile#L38

**Comment by josegonzalez** [comment]
Pull request welcome @ltalirz :)

**Comment by ltalirz** [comment]
I have never used Debian.

To your knowledge, is anybody using dokku on debian?
It seems to me that anybody on Debian would have hit this. 
How did they install dokku?

**Comment by josegonzalez** [comment]
Thats the dokku-daemon, but also not everyone uses this ansible repo.

The Makefile can probably check

```
OS=$(shell lsb_release -si)
```

And then do a conditional if that is `Ubuntu` or `Debian`.

**Comment by ltalirz** [comment]
hm... maybe it is because `socat` should be installed first on debian.
I'll check.

**Comment by ltalirz** [comment]
OK
