### ISSUE TITLE
Installation of latest dokku version fails due to version pinning.

### ISSUE THREAD

**Issue by cooperaj** [dokku/ansible-dokku#64]
## Description of problem
Installation of latest dokku version fails due to version pinning.

Ideally the dependencies of dokku would not be pinned but would match versions with whatever was required by dokku

### How reproducible
Set `dokku_version` to be 0.20.4 and installation will fail as it requires sshcommand >= 0.10.0 and the default pinned version is 0.9.0

#### Actual Results
Installation failure with error message from apt-get

#### Expected Results
Installation succeeds via installing all required dependencies for the selected version of dokku

#### Fix
Bumped `sshcommand_version` to 0.10.0 and it all works fine.

**Comment by ltalirz** [comment]
The versions of all relevant plugins, as well as dokku itself, has been bumped in b5847499a35fed230ce7891504b6a1ad6db4cc58 (long overdue).

I believe this addresses this issue - if not, feel free to reopen.
