### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#81]
@josegonzalez there have been a couple of commits since the last release; in particular bumps of dependency versions.
Would you mind dropping a new release?

**Comment by josegonzalez** [comment]
Done. Also, dont you have commit bit? I think you should be able to make releases...

**Comment by ltalirz** [comment]
Thanks @josegonzalez !

>  Also, dont you have commit bit? I think you should be able to make releases...

Ah, I didn't check and I didn't know whether you'd be ok with this.
For minor things like this, I'll then simply push a new tag next time.
