### ISSUE TITLE
support new `git:sync` command

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#94]
dokku 0.23 comes with a `git:sync` command https://github.com/dokku/dokku/pull/4297

This [replaces the dokku-clone](https://github.com/crisward/dokku-clone/issues/23#issuecomment-766392165) plugin; a fix for https://github.com/dokku/ansible-dokku/issues/88 is already built in.

My suggestion would be to deprecate the `dokku_clone` ansible module and replace the `dokku_git_sync` module with one that uses the dokku internals (and update the corresponding  [docs](https://github.com/dokku/ansible-dokku#dokku_git_sync) to no longer point to the commercial `git_sync` plugin).

@josegonzalez if you would like to do any of this, please go ahead.
I might have some time next weekend

**Comment by josegonzalez** [comment]
I won’t have time to contribute to non-core projects for a bit as I’m wrapping up my commercial admin tool. Feel free to take this on.
